---

- name: Setup environment
  hosts: prod
  remote_user: abhi
  become: yes
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - php
          - mariadb-server
          - firewalld
        state: latest

    - name: Enable and start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
 
    - name: Allow http ports using firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes

    - name: Writing index.html using template
      template:
        dest: /var/www/html/index.html
        src: jinja_facts.j2
...
