---
- name: Setup environment
  hosts: prod
  remote_user: abhi
  become: yes
  tasks:
    - name: Install packages
      yum:
        name: 
          - httpd
          - php
          - mariadb-server
          - firewalld
        state: latest
      tags: update  
      when: ansible_distribution == "RedHat"

    - name: Enable and start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb
 
    - name: Allow http ports using firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes

    - name: Writing index.html
      copy:
        dest: /var/www/html/index.html
        src: my_page.html
      tags: update

    - name: Restart service
      service:
        name: "{{ item }}"
        state: restarted
      loop: 
        - httpd
        - mariadb
      tags: update
...
