---
- name: Set issue content
  hosts: all
  remote_user: abhi
  become: yes
  tasks:
    - name: For dev group
      copy:
        content: "Development"
        dest: /etc/issue
      when: inventory_hostname in groups['dev']
   
    - name: For test group
      copy:
        content: "Test"
        dest: /etc/issue
      when: inventory_hostname in groups['test']

    - name: For prod group
      copy:
        content: "Production"
        dest: /etc/issue
      when: inventory_hostname in groups['prod']
...
