---
- name: install packages
  hosts: all
  remote_user: abhi
  become: yes
  tasks:
    - name: Install php, mariadb
      yum:
        name:
          - php
          - mariadb
        state: latest
      when: inventory_hostname in groups['dev'] or 
            inventory_hostname in groups['test'] or 
            inventory_hostname in groups['prod']
    
    - name: Install dev tools
      yum:
        name: "@Development tools"
        state: present
      when: inventory_hostname in groups['dev']

    - name: Update all packages
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']
...
